import { TabType } from '../types';

interface SearchItem {
  id: string;
  title: string;
  description: string;
  keywords: string[];
  tab: TabType;
  badge: string;
  badgeColor: string;
  action?: string; // e.g. score view id
}

export const SEARCH_INDEX: SearchItem[] = [
  // === EMERGENCY TAB ===
  { id: 'e-prep', title: 'Fase 0: Persiapan Resusitasi', description: 'Checklist tim, alat, estimasi BB, usia gestasi sebelum bayi lahir', keywords: ['persiapan','checklist','tim','alat','fase 0','briefing','nrp'], tab: 'emergency', badge: 'Resusitasi', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 'e-init', title: 'Langkah Awal (Golden Minute)', description: 'Skrining cepat, stimulasi, hangatkan, posisi, isap sekret', keywords: ['golden minute','initial steps','stimulasi','isap','suction','60 detik'], tab: 'emergency', badge: 'Resusitasi', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 'e-vtp', title: 'Ventilasi Tekanan Positif (VTP)', description: 'BVM/T-piece, teknik SRIBTA, evaluasi LDJ, 40–60x/menit', keywords: ['vtp','ventilasi','sribta','bvm','t-piece','ldj','frekuensi','napas'], tab: 'emergency', badge: 'Resusitasi', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 'e-cpap', title: 'CPAP Neonatus', description: 'PEEP 5–7 cmH₂O, indikasi, penyesuaian FiO2, evaluasi distres', keywords: ['cpap','peep','fio2','distres','napas','prematur'], tab: 'emergency', badge: 'Resusitasi', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 'e-kompr', title: 'Kompresi Dada Neonatus', description: 'Teknik dua jempol, rasio 3:1, 120 siklus/menit, kedalaman 1/3 AP', keywords: ['kompresi','dada','jantung','3:1','cardiac','compressions','dua jempol'], tab: 'emergency', badge: 'Resusitasi', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 'e-adr', title: 'Adrenalin / Epinefrin Neonatus', description: 'Dosis 0.1–0.3 mL/kg IV/IO (1:10.000), pengulangan tiap 3–5 menit', keywords: ['adrenalin','epinefrin','epinephrine','dosis','iv','io','obat','emergency'], tab: 'emergency', badge: 'Resusitasi', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 'e-vent', title: 'Setting Ventilator (Fase Alur Resusitasi)', description: 'Muncul otomatis saat alur resusitasi beralih ke dukungan napas invasif', keywords: ['ventilator','pip','peep','rr','ti','fio2','tidal volume','intubasi','ett'], tab: 'emergency', badge: 'Resusitasi', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 'e-anthr', title: 'Antropometri Neonatus', description: 'Input BB Lahir, PB, LK, LD, LiLA — autofill ke seluruh kalkulator', keywords: ['antropometri','bbl','pb','lk','ld','lila','berat lahir','panjang','kepala','dada'], tab: 'emergency', badge: 'Resusitasi', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },

  // === SCORES TAB ===
  { id: 's-apgar', title: 'Skor APGAR', description: 'Appearance, Pulse, Grimace, Activity, Respiration — menit 1, 5, 10', keywords: ['apgar','appearance','pulse','grimace','activity','respiration','warna','denyut','tonus'], tab: 'scores', badge: 'Skor', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 's-downe', title: 'Skor Downe', description: 'Penilaian distres napas: frekuensi, retraksi, sianosis, air entry, merintih', keywords: ['downe','distres napas','retraksi','sianosis','grunting','merintih','air entry'], tab: 'scores', badge: 'Skor', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 's-thomson', title: 'Skor Thomson (HIE)', description: 'Penilaian ensefalopati hipoksik-iskemik, indikasi terapi pendinginan', keywords: ['thomson','hie','ensefalopati','hipoksia','pendinginan','cooling','hipotermia terapeutik'], tab: 'scores', badge: 'Skor', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 's-ballard', title: 'Skor New Ballard', description: 'Estimasi usia gestasi dari kematangan neuromuskular dan fisik', keywords: ['ballard','usia gestasi','kematangan','neuromuskular','fisik','posture','square window','lanugo'], tab: 'scores', badge: 'Skor', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
  { id: 's-silverman', title: 'Skor Silverman-Anderson', description: 'RDS/distres napas prematur: gerak dada, retraksi, cuping hidung, grunting', keywords: ['silverman','anderson','rds','distres','retraksi','cuping','grunting','prematur'], tab: 'scores', badge: 'Skor', badgeColor: 'bg-rose-100 dark:bg-rose-950 text-rose-700 dark:text-rose-300' },

  // === THEORY TAB ===
  { id: 't-golden', title: 'The Golden Minute', description: 'Prinsip 60 detik pertama resusitasi, keputusan VTP berdasarkan HR dan napas', keywords: ['golden minute','60 detik','hr','napas','vtp','keputusan','nrp'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-trans', title: 'Transisi Kardiopulmonal', description: 'Fisiologi penutupan duktus arteriosus dan foramen ovale saat lahir', keywords: ['transisi','kardiopulmonal','duktus arteriosus','foramen ovale','fisiologi','sirkulasi'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-oksigen', title: 'Manajemen Oksigen Periresusitasi', description: 'Target SpO2 NRP 2021, titrasi FiO2, blender oksigen, hiperoksia', keywords: ['oksigen','spo2','fio2','blender','hiperoksia','target','nrp 2021'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-mekon', title: 'Mekonium / MSAF', description: 'Pendekatan NRP 2021: vigorous vs non-vigorous, tidak rutin suction orofaringeal', keywords: ['mekonium','msaf','meconium','vigorous','suction','aspirasi','air ketuban'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-intubasi', title: 'Intubasi ET & LMA', description: 'Ukuran ETT berdasarkan BB, kedalaman bibir, indikasi, teknik', keywords: ['intubasi','ett','lma','tube','ukuran','kedalaman','laringoskop','blade'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-kompr', title: 'Kompresi Dada Teori', description: 'Teknik dua jempol, titik penekanan, koordinasi VTP 3:1, evaluasi', keywords: ['kompresi','dua jempol','3:1','teknik','evaluasi','koordinasi'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-hipotermia', title: 'Hipotermia Terapeutik (TTM)', description: 'Pendinginan 33–34°C selama 72 jam untuk HIE sedang-berat ≥36 minggu', keywords: ['hipotermia','terapeutik','pendinginan','cooling','ttm','33','34','hie','thomson'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-dcc', title: 'Delayed Cord Clamping (DCC)', description: 'Penundaan pemotongan tali pusat ≥60 detik, manfaat untuk prematur dan aterm', keywords: ['dcc','delayed cord clamping','tali pusat','cord','pemotongan','ilcor'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-prematur', title: 'Resusitasi Neonatus Prematur', description: 'Pertimbangan khusus prematur: bungkus plastik, suhu, surfaktan, CPAP dini', keywords: ['prematur','preterm','bblr','plastik','suhu','surfaktan','cpap','dini'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-mrsopa', title: 'Langkah Koreksi Ventilasi (MR. SOPA)', description: 'Mask, Reposition, Suction, Open mouth, Pressure, Airway — koreksi VTP tidak efektif', keywords: ['mr sopa','mrsopa','koreksi','ventilasi','vtp','mask','reposition','suction','pressure','airway'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-farmako', title: 'Dosis & Farmakologi Darurat (Teori)', description: 'Epinefrin 0,01–0,03 mg/kg, volume expander NaCl/PRC 10 mL/kg, indikasi', keywords: ['epinefrin','adrenalin','farmakologi','volume expander','nacl','prc','dosis darurat'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-surfaktan', title: 'Terapi Surfaktan & LISA / MIST', description: 'Surfaktan selektif dini, LISA/MIST, poractant 200 mg/kg, OPTIMIST-A, RDS 2023', keywords: ['surfaktan','surfactant','lisa','mist','insure','poractant','curosurf','rds','optimist'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-kafein', title: 'Kafein Sitrat — Apnea Prematuritas', description: 'Loading 20 mg/kg, rumatan 5–10 mg/kg/hari, CAP trial, menurunkan BPD', keywords: ['kafein','caffeine','apnea','prematuritas','cap trial','bpd','sitrat','ekstubasi'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-stable', title: 'Program S.T.A.B.L.E', description: 'Sugar, Temperature, Airway, Blood pressure, Lab, Emotional — stabilisasi pra-transport', keywords: ['stable','stabilisasi','sugar','temperature','airway','blood pressure','transport','rujukan'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-hipoglikemia-t', title: 'Hipoglikemia Neonatus (Teori)', description: 'Ambang PES, dextrose gel 40%, bolus D10 2 mL/kg, GIR 4–8, Sugar Babies trial', keywords: ['hipoglikemia','gds','dextrose gel','d10','gir','pes','sugar babies','glukosa'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },
  { id: 't-neuroproteksi', title: 'Neuroproteksi & Persiapan Antenatal', description: 'Kortikosteroid antenatal & MgSO4 neuroproteksi (BEAM trial) untuk prematur', keywords: ['neuroproteksi','kortikosteroid','antenatal','deksametason','betametason','mgso4','magnesium','cerebral palsy','beam'], tab: 'theory', badge: 'Teori', badgeColor: 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300' },

  // === ADVANCED TAB (Pertumbuhan & Referensi) ===
  { id: 'a-lubchenco', title: 'Kurva Pertumbuhan Lubchenco', description: 'Klasifikasi AGA/SGA/LGA berdasarkan BB lahir dan usia gestasi', keywords: ['lubchenco','pertumbuhan','aga','sga','lga','kurva','berat lahir','percentil'], tab: 'advanced', badge: 'Pertumbuhan', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 'a-fenton', title: 'Kurva Pertumbuhan Fenton 2013', description: 'Klasifikasi SGA/AGA/LGA berdasarkan BB lahir dan GA 22–42 minggu, grafik persentil', keywords: ['fenton','pertumbuhan','sga','aga','lga','kurva','persentil','bb lahir','prematur'], tab: 'advanced', badge: 'Pertumbuhan', badgeColor: 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300' },
  { id: 's-flacc', title: 'Skor FLACC Nyeri Neonatus', description: 'Penilaian nyeri: wajah, kaki, aktivitas, tangisan, ketenangan — 0 hingga 10', keywords: ['flacc','nyeri','pain','neonatus','wajah','tangisan','kaki'], tab: 'scores', badge: 'Skor', badgeColor: 'bg-rose-100 dark:bg-rose-950 text-rose-700 dark:text-rose-300' },
  { id: 's-nips', title: 'Skor NIPS Nyeri Neonatus', description: 'Neonatal Infant Pain Scale — prematur dan aterm, evaluasi respons prosedural', keywords: ['nips','nyeri','pain','prematur','neonatal infant pain scale','prosedur'], tab: 'scores', badge: 'Skor', badgeColor: 'bg-rose-100 dark:bg-rose-950 text-rose-700 dark:text-rose-300' },

  // === CALCULATORS TAB (Kalkulator Klinis) ===
  { id: 'c-darurat', title: 'Kalkulator ETT & Dosis Darurat', description: 'Ukuran & kedalaman ETT, Adrenalin IV/ETT, NaHCO3, Nalokson, D10%, NaCl, Surfaktan — berdasarkan BB', keywords: ['ett','ukuran ett','endotrakeal','dosis darurat','adrenalin','nahco3','nalokson','d10','nacl','surfaktan'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-red-100 dark:bg-red-950 text-red-700 dark:text-red-300' },
  { id: 'c-ventilator', title: 'Setting Ventilator Mekanik Neonatus', description: 'PIP, PEEP, RR, Ti, FiO2, target gas darah & kriteria weaning per skenario (Normal/RDS/MAS/Apnea/PPHN)', keywords: ['ventilator','pip','peep','rr','ti','fio2','tidal volume','rds','mas','pphn','apnea','weaning','ekstubasi'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 'c-gds', title: 'Hipoglikemia Neonatus', description: 'Manajemen GDS rendah, bolus D10%, target >47 mg/dL', keywords: ['hipoglikemia','gds','glukosa','dextrose','d10','bolus','gula darah'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-rose-100 dark:bg-rose-950 text-rose-700 dark:text-rose-300' },
  { id: 'c-gir-dilution', title: 'Titrasi Cairan & GIR', description: 'Hitung konsentrasi dextrose, mixing D10/D40/WFI untuk target GIR', keywords: ['gir','dextrose','d10','d40','wfi','konsentrasi','pengenceran','campuran','titrasi'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-cyan-100 dark:bg-cyan-950 text-cyan-700 dark:text-cyan-300' },
  { id: 'c-gir', title: 'Kalkulator GIR', description: 'Glucose Infusion Rate — hitung kebutuhan dextrose mg/kg/menit', keywords: ['gir','glukosa','dextrose','infus','glucose infusion rate','hipoglikemia'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-amber-100 dark:bg-amber-950 text-amber-700 dark:text-amber-300' },
  { id: 'c-surf', title: 'Kalkulator Surfaktan', description: 'Dosis Poractant alfa (Curosurf) 200/100 mg/kg dan Beractant (Survanta)', keywords: ['surfaktan','curosurf','survanta','poractant','beractant','rds','prematur','dosis'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
  { id: 'c-ino', title: 'Kalkulator Drip Inotropik & Vasoaktif', description: 'Dopamin, Dobutamin, Epinefrin, Norepinefrin, Milrinon — konversi dosis ⇄ laju (mL/jam), rentang keamanan & Rule of 6', keywords: ['dopamin','dobutamin','epinefrin','adrenalin','norepinefrin','noradrenalin','milrinon','inotropik','vasoaktif','vasopresor','inotrope','mcg','dosis','laju','infus','drip','syok','rule of 6'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-cyan-100 dark:bg-cyan-950 text-cyan-700 dark:text-cyan-300' },
  { id: 'c-ino2', title: 'Pompa Syringe Inotropik (Pengenceran)', description: 'Hitung mg obat, volume spuit, dan kecepatan infus inotropik', keywords: ['dopamin','dobutamin','spuit','pengenceran','inotrope','syok','kardiovaskular','pompa'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 'c-fluid', title: 'Kalkulator Kebutuhan Cairan', description: 'Volume cairan harian neonatus berdasarkan hari kehidupan dan BB', keywords: ['cairan','fluid','mL/kg/hari','hari kehidupan','dol','aterm','prematur','bblr'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-sky-100 dark:bg-sky-950 text-sky-700 dark:text-sky-300' },
  { id: 'c-tpn', title: 'Kalkulator TPN Neonatus', description: 'Total Parenteral Nutrition: glukosa, protein, lipid, elektrolit harian untuk BBLR/prematur', keywords: ['tpn','parenteral','nutrisi','glukosa','protein','lipid','elektrolit','bblr','prematur'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-violet-100 dark:bg-violet-950 text-violet-700 dark:text-violet-300' },
  { id: 'c-abx', title: 'Kalkulator Antibiotik Neonatus', description: 'Ampisilin, Gentamisin, Cefotaxime — dosis berdasarkan GA, PMA, PNA', keywords: ['antibiotik','ampisilin','gentamisin','cefotaxime','eons','lons','sepsis','meningitis','dosis'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-rose-100 dark:bg-rose-950 text-rose-700 dark:text-rose-300' },
  { id: 'c-uvc', title: 'Kedalaman Kateter UVC & UAC', description: 'Hitung kedalaman umbilical venous/arterial catheter berdasarkan berat lahir', keywords: ['uvc','uac','kateter','umbilikal','kedalaman','vena','arteri','neonatus'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-teal-100 dark:bg-teal-950 text-teal-700 dark:text-teal-300' },
  { id: 'c-seizure', title: 'Manajemen Kejang Neonatus', description: 'Fenobarbital, Levetiracetam, Midazolam, Fenitoin — dosis loading dan maintenance', keywords: ['kejang','seizure','fenobarbital','levetiracetam','midazolam','fenitoin','neonatus','antikonvulsan'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-purple-100 dark:bg-purple-950 text-purple-700 dark:text-purple-300' },
  { id: 'c-bilirubin', title: 'Kalkulator Bilirubin & Fototerapi', description: 'Ambang fototerapi & transfusi tukar berdasarkan GA, usia jam, faktor risiko (AAP 2022)', keywords: ['bilirubin','fototerapi','ikterus','jaundice','transfusi tukar','aap','kuning'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-yellow-100 dark:bg-yellow-950 text-yellow-700 dark:text-yellow-300' },
  { id: 'c-convert', title: 'Konversi Unit Klinis', description: 'mcg/kg/mnt ke mL/jam, konsentrasi larutan, dosis obat, konversi berat', keywords: ['konversi','unit','mcg','mg','ml/jam','dosis','infus','konsentrasi'], tab: 'calculators', badge: 'Kalkulator', badgeColor: 'bg-orange-100 dark:bg-orange-950 text-orange-700 dark:text-orange-300' },

  { id: 'p-dashboard', title: 'Dashboard Pasien', description: 'Identitas pasien, skor klinis, status resusitasi, log tindakan terintegrasi', keywords: ['dashboard','pasien','identitas','skor','status','log','ringkasan'], tab: 'dashboard', badge: 'Dashboard', badgeColor: 'bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300' },
  { id: 'p-settings', title: 'Pengaturan & Info', description: 'Font, ukuran teks, mode tampilan, skema warna, cache, dan tentang aplikasi', keywords: ['pengaturan','setting','about','font','tema','dark mode','cache','reset'], tab: 'settings', badge: 'Pengaturan', badgeColor: 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300' },

  // === REFERENCES TAB ===
  { id: 'r-idai', title: 'IDAI 2022 — Resusitasi Neonatus', description: 'Panduan resusitasi neonatus Ikatan Dokter Anak Indonesia edisi 2022', keywords: ['idai','2022','resusitasi','panduan','indonesia','lokal'], tab: 'references', badge: 'Referensi', badgeColor: 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300' },
  { id: 'r-nrp', title: 'NRP 8th Edition (AAP/AHA 2021)', description: 'Neonatal Resuscitation Program edisi terbaru AAP dan AHA', keywords: ['nrp','aap','aha','2021','neonatal resuscitation program','8th'], tab: 'references', badge: 'Referensi', badgeColor: 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300' },
  { id: 'r-ilcor', title: 'ILCOR CoSTR 2022', description: 'International Liaison Committee on Resuscitation — Consensus on Science', keywords: ['ilcor','costr','2022','consensus','international'], tab: 'references', badge: 'Referensi', badgeColor: 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300' },
  { id: 'r-stable', title: 'S.T.A.B.L.E. Program 6th Ed', description: 'Post-resuscitation stabilization: Sugar, Temperature, Airway, Blood pressure, Lab, Emotional', keywords: ['stable','sugar','temperature','airway','blood pressure','lab','stabilisasi'], tab: 'references', badge: 'Referensi', badgeColor: 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300' },
];
